# Generated by Django 5.2 on 2025-04-13 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_demandeacte_type_acte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='conjoint',
        ),
        migrations.RemoveField(
            model_name='client',
            name='enfants',
        ),
    ]
